spring:
  application:
    name: ${APP_NAME:demo-jeager}
server:
  port: 8082
service:
  demo-jeager-customer:
    url: ${SERVICE_DEMO_JEAGER_CUSTOMER_URL:demo-jeager-customer:8084}
opentracing:
  jaeger:
    udp-sender:
      host: jaeger
      port: 6831