version: '3'
services:
  jeager:
    image: jaegertracing/all-in-one:1.18
    container_name: jaeger
    ports:
      - 5775:5775
      - 6831:6831
      - 6832:6832
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411
  demojeager:
    image: nnmuniz/demo-jeager:0.0.1-SNAPSHOT
    container_name: demo-jeager
    #restart: always
    ports:
      - 8082:8082
  demojeager2:
    image: nnmuniz/demo-jeager:0.0.1-SNAPSHOT
    container_name: demo-jeager2
    #restart: always
    ports:
      - 8083:8082
    environment:
      - APP_NAME=demo-jeage2
  demojeagerCustomer:
    image: nnmuniz/demo-jeager-customer:0.0.1-SNAPSHOT
    container_name: demo-jeager-customer
    #restart: always
    ports:
      - 8084:8084
    environment:
      - SERVICE_DEMO_JEAGER_CUSTOMER_URL=demo-jeager-customer:8084


#  sudo docker run -d --name jaeger \\n  -e COLLECTOR_ZIPKIN_HTTP_PORT=9411 \\n  -p 5775:5775/udp \\n  -p 6831:6831/udp \\n  -p 6832:6832/udp \\n  -p 5778:5778 \\n  -p 16686:16686 \\n  -p 14268:14268 \\n  -p 14250:14250 \\n  -p 9411:9411 \\n  jaegertracing/all-in-one:1.18
