version: '3.1'

services:

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.7
    container_name: keycloak
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev
#    volumes:
#      - ./keycloak/conf:/opt/keycloak/conf
#      - ./keycloak/realms:/opt/keycloak/data/import
#      - ./keycloak/themes:/opt/keycloak/themes