version: '3.1'

services:

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.7
    container_name: keycloak
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev

  springboot:
    image: keycloak-spring-security:0.0.1-SNAPSHOT
    container_name: springboot
    ports:
      - "8081:8081"