version: '3.5'

networks:
  kong-net:
    external: true

services:

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.7
    container_name: keycloak
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev
    networks:
      - kong-net

  springboot:
    image: keycloak-spring-security:0.0.3-SNAPSHOT
    container_name: springboot
    ports:
      - "8081:8081"
    environment:
      KEYCLOAK_ISSUER_URI: http://keycloak:8080/realms/corf
      KEYCLOAK_JWK_URI: http://keycloak:8080/realms/corf/protocol/openid-connect/certs
      SERVER_PORT: 8081
    networks:
      - kong-net