spring:
    application:
        name: padroes-codigo

service:
    av2:
        url: http://localhost:8081
    ak3:
        url: http://localhost:8082
    mainframe:
        url: http://localhost:8080