spring:
    profiles: default    
    jpa:
        database: POSTGRESQL
        hibernate:
          ddl-auto: update
        show-sql: true  
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: postgres
        
org:
  hibernate:
    envers:
      audit_table_suffix: _AUDIT_LOG        
        