version: '3'
services:
  redis:
    image: diegolirio/redis-as-database:0.0.6-SNAPSHOT
    container_name: redis
    restart: always
    ports:
      - 8080:8080
      - 80:8080
    environment:
      - REDIS_HOST=master.redis-cluster-re2.gyyko2.use1.cache.amazonaws.com
      - REDIS_PORT=6379
    networks:
      - elasticache
  #redis-customer:
  #  image: diegolirio/redis-ms-customer:0.0.1-SNAPSHOT
  #  container_name: redis-customer
  #  restart: always
  #  ports:
  #    - 8081:8080
  #  networks:
  #    - elasticache

networks:
  elasticache:
    driver: bridge
