AWSTemplateFormatVersion: 2010-09-09
Description: >
  Meu template EC2... 
  
Parameters:
  myKeySSH:
    Description: My Key SSH
    Type: AWS::EC2::KeyPair::KeyName
    Default: First
  environment:
    Description: Ambiente de desenvolvimento
    Type: String
    Default: develop
  #subNet:
  #  Description: SubNet
  #  Type: String
  #  Default:  
  
Mappings:
  myInstanceMap:
    us-east-2: 
      "HVM64": ami-07c1207a9d40bc3bd 
    us-east-1:
      "HVM64": ami-0d7a95455cac37c33
    sa-east-1:
      "HVM64": ami-077d5d3682940b34a
  
#Conditions:
#  CriarOutraInstanciaEC2: !Equals [!Ref meuAmbiente, dev]
 
Resources:
  EC2PublicGameON:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref myKeySSH
      ImageId: !FindInMap [ myInstanceMap, !Ref 'AWS::Region', HVM64 ]
      InstanceType: t2.nano
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: "0"
          SubnetId: !ImportValue VPC-GameON-SubNetPublicaID
          GroupSet:
            - !ImportValue VPC-GameON-SGID
      Monitoring: false
      #SecurityGroupIds:
        #- !ImportValue infraestructureVPC-SGID
      #SubnetId: !ImportValue infraestructureVPC-SubNetPublicaID
      UserData: !Base64 |
        #!/bin/bash -ex
        apt update
        apt install docker.io -y
        curl -L https://github.com/docker/compose/releases/download/1.18.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose 
        chmod +x /usr/local/bin/docker-compose
        wget https://raw.githubusercontent.com/diegolirio/aws/master/docker-compose.yml
        sudo docker-compose up -d     
        export REDIS_HOST="master.redis-cluster-re2.gyyko2.use1.cache.amazonaws.com"
        export REDIS_PORT="6379"

  # MyVolume:
  #   Type: AWS::EC2::Volume
  #   Properties: 
  #     Size: 8
  #     VolumeType: sc1
  #     AvailabilityZone: !GetAtt EC2PublicGameON.AvailabilityZone        
    
Outputs:
  EC2PublicGameONExport:
    Description: Game ON Export EC2
    Value: !Ref EC2PublicGameON
    Export:
      Name: !Sub "${AWS::StackName}-EC2GameONID"